# Generated by Django 5.1.4 on 2025-02-26 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('BuyerInfo', models.JSONField(default=dict)),
                ('AmazonOrderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('EarliestDeliveryDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('EarliestShipDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('SalesChannel', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('AutomatedShippingSettings', models.JSONField(default=dict)),
                ('OrderStatus', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('NumberOfItemsShipped', models.IntegerField(default=0)),
                ('OrderType', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('IsPremiumOrder', models.BooleanField(default=False)),
                ('IsPrime', models.BooleanField(default=False)),
                ('FulfillmentChannel', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('NumberOfItemsUnshipped', models.IntegerField(default=0)),
                ('HasRegulatedItems', models.BooleanField(default=False)),
                ('IsReplacementOrder', models.BooleanField(default=False)),
                ('IsSoldByAB', models.BooleanField(default=False)),
                ('LatestShipDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('ShipServiceLevel', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('DefaultShipFromLocationAddress', models.JSONField(default=dict)),
                ('IsISPU', models.BooleanField(default=False)),
                ('MarketplaceId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('LatestDeliveryDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('PurchaseDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('ShippingAddress', models.JSONField(default=dict)),
                ('IsAccessPointOrder', models.BooleanField(default=False)),
                ('PaymentMethod', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('IsBusinessOrder', models.BooleanField(default=False)),
                ('OrderTotal', models.JSONField(default=dict)),
                ('PaymentMethodDetails', models.JSONField(default=list)),
                ('IsGlobalExpressEnabled', models.BooleanField(default=False)),
                ('LastUpdateDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('ShipmentServiceLevelCategory', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('TaxCollection', models.JSONField(default=dict)),
                ('ProductInfo', models.JSONField(default=dict)),
                ('ItemTax', models.JSONField(default=dict)),
                ('QuantityShipped', models.IntegerField(default=0)),
                ('BuyerRequestedCancel', models.JSONField(default=dict)),
                ('ItemPrice', models.JSONField(default=dict)),
                ('ASIN', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('SellerSKU', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('IsGift', models.BooleanField(default=False)),
                ('ConditionSubtypeId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('IsTransparency', models.BooleanField(default=False)),
                ('QuantityOrdered', models.IntegerField(default=0)),
                ('PromotionDiscountTax', models.JSONField(default=dict)),
                ('ConditionId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('PromotionDiscount', models.JSONField(default=dict)),
                ('OrderItemId', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('profit', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('ASIN', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('QuantityLeft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=255)),
                ('purchase_from', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_with', models.CharField(blank=True, max_length=255)),
                ('asin', models.CharField(blank=True, max_length=20)),
                ('profit', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('edit', models.BooleanField(default=False)),
                ('invoice_path', models.CharField(default='', max_length=255)),
                ('available_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
