# Generated by Django 5.1.4 on 2025-02-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pack_of',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
