# Generated by Django 5.1.4 on 2025-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchaseorder_pack_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='have_profit',
            field=models.BooleanField(default=False),
        ),
    ]
