# Generated by Django 5.1.4 on 2025-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_errororders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errororders',
            old_name='id_type',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='errororders',
            name='id_value',
        ),
        migrations.AddField(
            model_name='errororders',
            name='reason',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='have_profit',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
