# Generated by Django 5.1.7 on 2025-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_type_errororders_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fba_fee',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_discount',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10, null=True),
        ),
    ]
