from django.db import models
import uuid

class PurchaseOrder(models.Model):
  order_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
  item = models.CharField(max_length=255, blank=True)
  purchase_from = models.CharField(max_length=255, blank=True)
  quantity = models.IntegerField(blank=True, null=True)
  amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
  pack_of = models.IntegerField(blank=True, null=True, default=1)
  amount_per_unit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
  paid_with = models.CharField(max_length=255, blank=True)
  asin = models.CharField(max_length=20, blank=True)
  profit = models.DecimalField(max_digits=10, decimal_places=3, default=0)
  profit_percentage = models.DecimalField(max_digits=10, decimal_places=3, default=0)
  edit = models.BooleanField(default=False)
  invoice_path = models.CharField(default='',max_length=255)
  available_quantity = models.IntegerField(blank=True, null=True)
  created_at = models.DateTimeField(auto_now_add=True)


class Order(models.Model):
    BuyerInfo = models.JSONField(default=dict)
    AmazonOrderId = models.CharField(max_length=100, primary_key=True)
    EarliestDeliveryDate = models.DateTimeField(default=None, null=True, blank=True)
    EarliestShipDate = models.DateTimeField(default=None, null=True, blank=True)
    SalesChannel = models.CharField(max_length=100,default=None, null=True, blank=True)
    AutomatedShippingSettings = models.JSONField(default=dict)
    OrderStatus = models.CharField(max_length=50,default=None, null=True, blank=True)
    NumberOfItemsShipped = models.IntegerField(default=0)
    OrderType = models.CharField(max_length=50,default=None, null=True, blank=True)
    IsPremiumOrder = models.BooleanField(default=False)
    IsPrime = models.BooleanField(default=False)
    FulfillmentChannel = models.CharField(max_length=50,default=None, null=True, blank=True)
    NumberOfItemsUnshipped = models.IntegerField(default=0)
    HasRegulatedItems = models.BooleanField(default=False)
    IsReplacementOrder = models.BooleanField(default=False)
    IsSoldByAB = models.BooleanField(default=False)
    LatestShipDate = models.DateTimeField(default=None, null=True, blank=True)
    ShipServiceLevel = models.CharField(max_length=50,default=None, null=True, blank=True)
    DefaultShipFromLocationAddress = models.JSONField(default=dict)
    IsISPU = models.BooleanField(default=False)
    MarketplaceId = models.CharField(max_length=50,default=None, null=True, blank=True)
    LatestDeliveryDate = models.DateTimeField(default=None, null=True, blank=True)
    PurchaseDate = models.DateTimeField(default=None, null=True, blank=True)
    ShippingAddress = models.JSONField(default=dict)
    IsAccessPointOrder = models.BooleanField(default=False)
    PaymentMethod = models.CharField(max_length=50,default=None, null=True, blank=True)
    IsBusinessOrder = models.BooleanField(default=False)
    OrderTotal = models.JSONField(default=dict)
    PaymentMethodDetails = models.JSONField(default=list)
    IsGlobalExpressEnabled = models.BooleanField(default=False)
    LastUpdateDate = models.DateTimeField(default=None, null=True, blank=True)
    ShipmentServiceLevelCategory = models.CharField(max_length=50,default=None, null=True, blank=True)
    TaxCollection = models.JSONField(default=dict)
    ProductInfo = models.JSONField(default=dict)
    ItemTax = models.JSONField(default=dict)
    QuantityShipped = models.IntegerField(default=0)
    BuyerRequestedCancel = models.JSONField(default=dict)
    ItemPrice = models.JSONField(default=dict)
    ASIN = models.CharField(max_length=50,default=None, null=True, blank=True)
    SellerSKU = models.CharField(max_length=50,default=None, null=True, blank=True)
    Title = models.CharField(max_length=255,default=None, null=True, blank=True)
    IsGift = models.BooleanField(default=False)
    ConditionSubtypeId = models.CharField(max_length=50,default=None, null=True, blank=True)
    IsTransparency = models.BooleanField(default=False)
    QuantityOrdered = models.IntegerField(default=0)
    PromotionDiscountTax = models.JSONField(default=dict)
    ConditionId = models.CharField(max_length=50,default=None, null=True, blank=True)
    PromotionDiscount = models.JSONField(default=dict)
    OrderItemId = models.CharField(max_length=100,default=None, null=True, blank=True)
    have_profit = models.BooleanField(default=False,db_index=True)
    profit = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    profit_percentage = models.DecimalField(max_digits=10, decimal_places=3, default=0)

    def __str__(self):
        return self.AmazonOrderId

class OrderItem(models.Model):
   ASIN = models.CharField(max_length=50, primary_key=True)
   QuantityLeft = models.IntegerField(default=0)

class ErrorOrders(models.Model):
   error_order_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
   order_id = models.CharField(max_length=50, default="")
   reason = models.CharField(max_length=20, default="")
   data = models.JSONField(default=dict)