from django.db import models
import uuid

class PurchaseOrder(models.Model):
  order_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
  item = models.CharField(max_length=255, blank=True)
  purchase_from = models.CharField(max_length=255, blank=True)
  quantity = models.IntegerField(blank=True, null=True)
  amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
  amount_per_unit = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
  paid_with = models.CharField(max_length=255, blank=True)
  asin = models.CharField(max_length=20, blank=True)
  profit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
  profit_percentage = models.DecimalField(max_digits=10, decimal_places=2, default=0)
  edit = models.BooleanField(default=False)
  invoice_path = models.CharField(default='',max_length=255)
  available_quantity = models.IntegerField(blank=True, null=True)
  created_at = models.DateTimeField(auto_now_add=True)


class Order(models.Model):
    BuyerInfo = models.JSONField(default=dict)
    AmazonOrderId = models.CharField(max_length=100, primary_key=True)
    EarliestDeliveryDate = models.DateTimeField()
    EarliestShipDate = models.DateTimeField()
    SalesChannel = models.CharField(max_length=100)
    AutomatedShippingSettings = models.JSONField(default=dict)
    OrderStatus = models.CharField(max_length=50)
    NumberOfItemsShipped = models.IntegerField(default=0)
    OrderType = models.CharField(max_length=50)
    IsPremiumOrder = models.BooleanField(default=False)
    IsPrime = models.BooleanField(default=False)
    FulfillmentChannel = models.CharField(max_length=50)
    NumberOfItemsUnshipped = models.IntegerField(default=0)
    HasRegulatedItems = models.BooleanField(default=False)
    IsReplacementOrder = models.BooleanField(default=False)
    IsSoldByAB = models.BooleanField(default=False)
    LatestShipDate = models.DateTimeField()
    ShipServiceLevel = models.CharField(max_length=50)
    DefaultShipFromLocationAddress = models.JSONField(default=dict)
    IsISPU = models.BooleanField(default=False)
    MarketplaceId = models.CharField(max_length=50)
    LatestDeliveryDate = models.DateTimeField()
    PurchaseDate = models.DateTimeField()
    ShippingAddress = models.JSONField(default=dict)
    IsAccessPointOrder = models.BooleanField(default=False)
    PaymentMethod = models.CharField(max_length=50)
    IsBusinessOrder = models.BooleanField(default=False)
    OrderTotal = models.JSONField(default=dict)
    PaymentMethodDetails = models.JSONField(default=list)
    IsGlobalExpressEnabled = models.BooleanField(default=False)
    LastUpdateDate = models.DateTimeField()
    ShipmentServiceLevelCategory = models.CharField(max_length=50)
    TaxCollection = models.JSONField(default=dict)
    ProductInfo = models.JSONField(default=dict)
    ItemTax = models.JSONField(default=dict)
    QuantityShipped = models.IntegerField(default=0)
    BuyerRequestedCancel = models.JSONField(default=dict)
    ItemPrice = models.JSONField(default=dict)
    ASIN = models.CharField(max_length=50)
    SellerSKU = models.CharField(max_length=50)
    Title = models.CharField(max_length=255)
    IsGift = models.BooleanField(default=False)
    ConditionSubtypeId = models.CharField(max_length=50)
    IsTransparency = models.BooleanField(default=False)
    QuantityOrdered = models.IntegerField(default=0)
    PromotionDiscountTax = models.JSONField(default=dict)
    ConditionId = models.CharField(max_length=50)
    PromotionDiscount = models.JSONField(default=dict)
    OrderItemId = models.CharField(max_length=100)

    def __str__(self):
        return self.AmazonOrderId

class OrderItem(models.Model):
   ASIN = models.CharField(max_length=50)
   QuantityLeft = models.IntegerField(default=0)